# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
aliases:
  - &base-image
    - image: circleci/node:10.11
  - &restore-cache
    keys:
      - v1-dependencies-{{ checksum "package.json" }}
      - v1-dependencies-
  - &save-cache
    paths:
      - node_modules
    key: v1-dependencies-{{ checksum "package.json" }}
jobs:
  build:
    docker: *base-image
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - save_cache: *save-cache
  lint:
    docker: *base-image
    working_directory: ~/repo
    steps:
      - restore_cache: *restore-cache
      - run: yarn lint
  flow:
    docker: *base-image
    working_directory: ~/repo
    steps:
      - restore_cache: *restore-cache
      - run: yarn flow
workflows:
  version: 2
  commit:
    jobs:
      - build
      - lint:
          requires:
            - build
      - flow:
          requires:
            - build
